//
//  RNAlertSymbol.h
//  
//
//  Created by Rayhan on 6/23/18.
//  Copyright © 2018 Rayhan Janam. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface RNAlertSymbol : NSObject

// Colors
+ (UIColor*)gray;

// Drawing Methods
+ (void)drawCheckMarkWithFrame: (CGRect)frame;
+ (void)drawExclamationMarkWithFrame: (CGRect)frame;

@end
